version: "3.7"

services:
  ServerDiscordBot:
    container_name: ServerDiscordBot
    image: darrenoosthuizen/serverdiscordbot:1.0.1
    restart: unless-stopped
    network_mode: host
    build:
      context: ./
      dockerfile: ./dockerfile
    
